### PR TITLE
Change default value of Method RequestParameters from {} to true

### PR DESCRIPTION
**Pull request by geetchoubey**
Per the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-requestparameters), method.Properties.RequestParameters only accepts a string;boolean pair object.
The issue:
When using the plugin like:
```yaml
events:
  - http:
      path: pathPart
      method: get
      cors: true
      caching:
        enabled: true
        cacheKeyParameters:
          - name: request.querystring.limit
          - name: request.header.Accept
          - name: request.header.Authorization
```
The plugin modifies the cloudformation: 
```json
"ApiGatewayMethodMyApiGet": {
  "Type": "AWS::ApiGateway::Method",
  "Properties": {
    "HttpMethod": "GET",
    "RequestParameters": {
      "method.request.querystring.limit": {},
      "method.request.header.Accept": {},
      "method.request.header.Authorization": {}
    },
```

Which leads to the following error:
```
Properties validation failed for resource ApiGatewayMethodMyApiGet with message:
#/RequestParameters/method.request.header.Accept: #: no subschema matched out of the total 2 subschemas
#/RequestParameters/method.request.header.Accept: expected type: Boolean, found: JSONObject
#/RequestParameters/method.request.header.Accept: expected type: String, found: JSONObject
#/RequestParameters/method.request.querystring.limit: #: no subschema matched out of the total 2 subschemas
#/RequestParameters/method.request.querystring.limit: expected type: Boolean, found: JSONObject
#/RequestParameters/method.request.querystring.limit: expected type: String, found: JSONObject
#/RequestParameters/method.request.header.Authorization: #: no subschema matched out of the total 2 subschemas
#/RequestParameters/method.request.header.Authorization: expected type: Boolean, found: JSONObject
#/RequestParameters/method.request.header.Authorization: expected type: String, found: JSONObject

```

This PR changes the default values to `true` instead of `{}` and updates related unit tests.

### CODE REVIEW

**Comment by slatermorgan** [comment]
Currently experiencing this in our deployment pipeline, is this due to AWS  changing validation their end?

**Comment by geetchoubey** [comment]
> Currently experiencing this in our deployment pipeline. Why is this suddently an issue? have AWS changed their Cloud Formation validation?

That is surprising to our team as well. We have had a service running for a long time until this week we noticed the pipeline failing due to this plugin.

**Comment by DianaIonita** [comment]
Hi @geetchoubey,

Thanks for raising this issue and creating a fix. I haven't been able to reproduce the problem you've seen, but the plugin works fine with your changes, so I'll just create a release and see what happens 😄

**Comment by DianaIonita** [comment]
Released [in this version](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.10.3).

**Comment by slatermorgan** [comment]
From the AWS docs linked above:

> "The value associated with the key is a Boolean flag indicating whether the parameter is required (true) or optional (false). The method request parameter names defined here are available in Integration to be mapped to integration request parameters or templates."

Doesnt this mean that optional parameters I want to add to the `cacheKeyParameters` block are now forced to be required?

I am seeing in my lambda functions, parameters which were previously not required are now required.

**Pull request merged**
