### PR TITLE
Support for shared api gateway

### PR DESCRIPTION
**Pull request by apalumbo**
- [x] Added apiGatewayIsShared to configuration
- [x] Added test for verify it is implemented correctly
- [x] Aligned fixture builder to support new configuration

### CODE REVIEW

**Comment by apalumbo** [comment]
I've added the tests, I could refactor a little bit to avoid duplication in testing, but to be honest I focused on adding the feature and reduce the risk of breaking tests

**Comment by apalumbo** [comment]
Hi @DianaIonita, maybe I am wrong but from the code I understood that the encription is set only on the endpoints and not globally, am I wrong?

**Comment by DianaIonita** [comment]
You can configure it both globally and per endpoint.

This is how configuration per stage looks like in API Gateway:
image

And this is for an endpoint:

image

In the code, the `createPatchForStage` method configures global settings, while `patchForMethod` configures endpoint settings.

**Comment by apalumbo** [comment]
Ok, I was a bit confused as I didn't have time to go deep about the line https://github.com/DianaIonita/serverless-api-gateway-caching/blob/develop/src/stageCache.js#L35

Where there is the expression ''/*/*/caching/dataEncrypted'' , I thought that it will do a nested replacement

**Comment by DianaIonita** [comment]
> Where there is the expression ''///caching/dataEncrypted'' , I thought that it will do a nested replacement

I'm not sure I'm following. Correct me if I'm wrong, but the scenario you're working with is this:
- Serverless Stack `A` has defined API Gateway caching settings for Rest API deployment `R`.
- Stack `A` has been deployed.
- Serverless Stack `B` is referencing Rest API deployment `R` and has also defined caching settings. In its settings, it specifies `apiGatewayIsShared: true`.

As the code is currently written, when stack `B` is deployed, data encryption settings will be applied based on stack `B`'s caching settings, overwriting whatever stack `A` has set up. However, all other stage settings defined in stack `B` will not be considered.
That doesn't feel intuitive to me, I think it should follow an all-or-nothing approach.

**Comment by apalumbo** [comment]
Ok, it's true if it is shared it should not be set at all.
But I was worried as by the docs at https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/#methodSettings 

> Keys (designated as /{method_setting_key below) are method paths defined as {resource_path}/{http_method} for an individual method override, or /*/* for overriding all methods in the stage

I was worried about the fact that /*/* could update all the functions, but I think it's used more like a default

**Pull request merged**
